# Generated by Django 5.0.4 on 2024-06-05 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0003_department_dept_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxelType',
            fields=[
                ('axel_id', models.AutoField(primary_key=True, serialize=False)),
                ('axel_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.AutoField(primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModeOfShipment',
            fields=[
                ('ms_id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_of_shipment', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckCapacity',
            fields=[
                ('tc_id', models.AutoField(primary_key=True, serialize=False)),
                ('truck_capacity', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckLength',
            fields=[
                ('tl_id', models.AutoField(primary_key=True, serialize=False)),
                ('truck_length', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('tt_id', models.AutoField(primary_key=True, serialize=False)),
                ('truck_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_point', models.CharField(blank=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('landline_number', models.CharField(blank=True, max_length=11, null=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('DO_BE_PO_NO', models.IntegerField()),
                ('CONSIGNMENT_DESCRIPTION', models.CharField(max_length=500)),
                ('seal_no', models.IntegerField()),
                ('container_no', models.IntegerField()),
                ('loading_by_consignor', models.CharField(max_length=3)),
                ('unloading_by_consignee', models.CharField(max_length=3)),
                ('freight_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planned_loading_datetime', models.DateTimeField()),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planned_unloading_datetime', models.DateTimeField()),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_days', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance', models.CharField(blank=True, max_length=100, null=True)),
                ('axel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiry.axeltype')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiry.cluster')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.companyprofile')),
                ('destination_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_address', to='inquiry.address')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiry.division')),
                ('pickup_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_address', to='inquiry.address')),
                ('mode_of_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiry.modeofshipment')),
                ('truck_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiry.truckcapacity')),
                ('length', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiry.trucklength')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiry.trucktype')),
            ],
        ),
    ]
