# Generated by Django 5.0.4 on 2024-06-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_initial'),
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='axel_type',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='destination_address',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='division',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='length',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='mode_of_shipment',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='order_quantity',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='truck_details',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='truck_type',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='axel_type',
            field=models.ManyToManyField(to='inquiry.axeltype'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='cluster',
            field=models.ManyToManyField(blank=True, null=True, to='inquiry.cluster'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='customer',
            field=models.ManyToManyField(to='authapp.companyprofile'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='destination_address',
            field=models.ManyToManyField(blank=True, null=True, related_name='destination_address', to='inquiry.address'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='division',
            field=models.ManyToManyField(blank=True, null=True, to='inquiry.division'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='length',
            field=models.ManyToManyField(to='inquiry.trucklength'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='mode_of_shipment',
            field=models.ManyToManyField(to='inquiry.modeofshipment'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='order_quantity',
            field=models.ManyToManyField(to='inquiry.orderquantity'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='pickup_address',
            field=models.ManyToManyField(blank=True, null=True, related_name='pickup_address', to='inquiry.address'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='truck_details',
            field=models.ManyToManyField(to='inquiry.truckdetails'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='truck_type',
            field=models.ManyToManyField(to='inquiry.trucktype'),
        ),
    ]
