# Generated by Django 5.0.4 on 2024-06-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_remove_inquiry_axel_type_remove_inquiry_cluster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='DO_BE_PO_NO',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='container_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='freight_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='price_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='seal_no',
            field=models.CharField(max_length=100),
        ),
    ]
