# Generated by Django 5.0.4 on 2024-06-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_alter_inquiry_do_be_po_no_alter_inquiry_container_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='planned_loading_datetime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='planned_unloading_datetime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
