# Generated by Django 5.0.4 on 2024-06-05 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_alter_inquiry_freight_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiry.cluster'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiry.division'),
        ),
    ]
