# Generated by Django 5.0.4 on 2024-06-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0004_alter_inquiry_planned_loading_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDays',
            fields=[
                ('cd_id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_days', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_terms', models.CharField(max_length=100)),
            ],
        ),
    ]
