# Generated by Django 5.0.4 on 2024-06-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0004_alter_inquiry_cluster_alter_inquiry_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='destination_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_address', to='inquiry.address'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='pickup_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_address', to='inquiry.address'),
        ),
    ]
