# Generated by Django 5.0.4 on 2024-06-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0005_creditdays_paymentterms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditdays',
            name='credit_days',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentterms',
            name='payment_terms',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
