# Generated by Django 5.0.4 on 2024-06-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0006_alter_creditdays_credit_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='credit_days',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='payment_terms',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='credit_days',
            field=models.ManyToManyField(blank=True, null=True, to='inquiry.creditdays'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='payment_terms',
            field=models.ManyToManyField(blank=True, null=True, to='inquiry.paymentterms'),
        ),
    ]
