# Generated by Django 5.0.4 on 2024-06-07 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0008_truckdetails_truck_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckdetails',
            name='truck_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiry.trucktype'),
        ),
    ]
