# Generated by Django 5.0.4 on 2024-06-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0011_transporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='transporter_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
