# Generated by Django 5.0.4 on 2024-06-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0012_transporter_transporter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditdays',
            name='credit_days',
            field=models.CharField(max_length=100),
        ),
    ]
