# Generated by Django 5.0.4 on 2024-06-12 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0015_inquiry_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inquiry.inquiry')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inquiry.transporter')),
            ],
        ),
    ]
