# Generated by Django 5.0.4 on 2024-06-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_initial'),
        ('inquiry', '0016_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='inquiry',
        ),
        migrations.AddField(
            model_name='assign',
            name='CONSIGNMENT_DESCRIPTION',
            field=models.CharField(default='no desc', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assign',
            name='DO_BE_PO_NO',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assign',
            name='axel_type',
            field=models.ManyToManyField(to='inquiry.axeltype'),
        ),
        migrations.AddField(
            model_name='assign',
            name='clusters',
            field=models.ManyToManyField(blank=True, to='inquiry.cluster'),
        ),
        migrations.AddField(
            model_name='assign',
            name='container_no',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assign',
            name='credit_days',
            field=models.ManyToManyField(blank=True, to='inquiry.creditdays'),
        ),
        migrations.AddField(
            model_name='assign',
            name='customer',
            field=models.ManyToManyField(to='authapp.companyprofile'),
        ),
        migrations.AddField(
            model_name='assign',
            name='destination_addresses',
            field=models.ManyToManyField(blank=True, related_name='assign_destination_addresses', to='inquiry.address'),
        ),
        migrations.AddField(
            model_name='assign',
            name='divisions',
            field=models.ManyToManyField(blank=True, to='inquiry.division'),
        ),
        migrations.AddField(
            model_name='assign',
            name='freight_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assign',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assign',
            name='length',
            field=models.ManyToManyField(to='inquiry.trucklength'),
        ),
        migrations.AddField(
            model_name='assign',
            name='loading_by_consignor',
            field=models.CharField(default='yes', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assign',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assign',
            name='mode_of_shipment',
            field=models.ManyToManyField(to='inquiry.modeofshipment'),
        ),
        migrations.AddField(
            model_name='assign',
            name='order_quantity',
            field=models.ManyToManyField(to='inquiry.orderquantity'),
        ),
        migrations.AddField(
            model_name='assign',
            name='payment_terms',
            field=models.ManyToManyField(blank=True, to='inquiry.paymentterms'),
        ),
        migrations.AddField(
            model_name='assign',
            name='pickup_addresses',
            field=models.ManyToManyField(blank=True, related_name='assign_pickup_addresses', to='inquiry.address'),
        ),
        migrations.AddField(
            model_name='assign',
            name='planned_loading_datetime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assign',
            name='planned_unloading_datetime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assign',
            name='price_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assign',
            name='seal_no',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assign',
            name='truck_details',
            field=models.ManyToManyField(to='inquiry.truckdetails'),
        ),
        migrations.AddField(
            model_name='assign',
            name='truck_type',
            field=models.ManyToManyField(to='inquiry.trucktype'),
        ),
        migrations.AddField(
            model_name='assign',
            name='unloading_by_consignee',
            field=models.CharField(default='yes', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assign',
            name='unmerged_order_quantities',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
