from django.db import models
from authapp.models import CompanyProfile
# Create your models here.
# model named CompanyModules which shows all the modules each company has, by default when user signs up we will add a list of modules for that company in this model through our backed, this is necessary as on dashboard, the module name which are shown will be dynamically coming from this model alone, also links will be dynamically generated by baseurl/code for each tuple will store here cm_id, company, module_code, module_name. these 4 fields when someone logs in we will do a get operation on this database and get all entries with company_id as query parameter. then each block on dashboard will be dynamically filled by /module_code , in name by module name.....module code is slug of module name


class CompanyModules(models.Model):
    cm_id=models.AutoField(primary_key=True)
    company = models.ForeignKey(CompanyProfile, on_delete=models.CASCADE)
    module_code=models.SlugField(max_length=100, unique=True)
    module_name=models.CharField(max_length=200)

    def __str__(self):
        return self.module_name