# Generated by Django 5.0.4 on 2024-06-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_desc',
            field=models.TextField(blank=True),
        ),
    ]
