# Generated by Django 5.0.4 on 2024-05-23 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModules',
            fields=[
                ('cm_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_code', models.SlugField(max_length=100, unique=True)),
                ('module_name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.companyprofile')),
            ],
        ),
    ]
