# Generated by Django 5.0.4 on 2024-05-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodules',
            name='module_code',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
