# Generated by Django 5.0.4 on 2024-05-23 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('home', '0002_alter_companymodules_module_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_code', models.SlugField(blank=True, max_length=100, unique=True)),
                ('module_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyModule',
            fields=[
                ('cm_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.companyprofile')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.module')),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyModules',
        ),
    ]
